1st rk
java-park-mail-ru/shark_team-02-2018 pull request #1
Opened 2018-02-27 21:24 UTC by 3kybika

2018-02-28 08:25 UTC, isopov commented
1. Мы в требования вынесли, что тут должны быть осмысленные идентификаторы
```
	<groupId>com</groupId>
	<artifactId>demo</artifactId>
```
2. Названия папок для пакетов начинаются с большой буквы, в декларациях пакетов с маленькой буквы - в моей IDE это не компилится. (Должны быть везде с маленькой буквы - такой в java naming convention). И название проекта в корневой пакет тоже добавьте.
3. Почистите комментарии. Вот такой не несет никакой дополнительной информации и непонятно зачем нужен:
```
        //Получаем пользователя
        final User currentUser = userService.getUser(login);
```
4. Зависимости spring-boot-starter-websocket & spring-boot-starter-jdbc вам потом понадобятся, но сейчас непонятно зачем они нужны. И конфиг подключения к базе, который в реальности не используется. Неработающего кода луше не оставлять - хорошо бы переместить этот код в другую ветку.
5. `@SuppressWarnings("unused")` на реально используемых методах и классах стоит удалить (и если они будут подсвечиваться в IDE как неиспользуемые - разобраться с IDE, а не добавлять suppress) На простых getter-ах и setter-ах тоже suppress оставлять не стоит, а настроить IDE, чтобы она на них не ругалась.
6. Мне кажется при logout-е лучше сессию убивать полностью через `httpSession.invalidate()`, а не только логин (или идентификатор пользователя) очищать.
7. Вот такую декларацию 
```
    @RequestMapping(path = "/logout",
            method = RequestMethod.POST,
            consumes = "application/json",
            produces = "application/json"
    )
```
Скорее всего можно заменить на более короткую - `@PostMapping("/logout")`. json придет из того, что это `@RestController`.
8. `ResponseEntity` - raw-тип не надо использовать, параметризуйте хотя вопросом.

2018-02-28 08:27 UTC, isopov requested changes
Замечания в комментарии.

2018-02-28 22:09 UTC, 3kybika commented
Вроде всё пофиксил. 
Вебсокеты и jdbc поэтому заранее и прикрутил - раз все равно понадобятся. Пока убрал.  
На unused IDE не ругается.
 ToDo-комменты можно пока оставить? Не принципиально - могу удалить.

2018-03-07 08:01 UTC, isopov commented
Прошу прощения за задержку.

1. `<artifactId>api</artifactId>` - shark туда напишите. Я не описал проблему - у меня в IDE открыто одновременно несколько десятков проектов, и по названию "api", "backend", "demo" я ничего найти не могу.
2. `<version>1.5.10.RELEASE</version>` - на этот РК можно оставить, но в будущем надо перейти на 2.0.0.RELEASE (или более позднюю, если она уже выйдет) - чисто для удобства, когда начнем работать с тестам, БД, вебсокетами (и может вы что-то еще захотите добавить в проект) там появятся маленькие несовместимости между двумя мажорными версиями, и проще будет, если все будут делать на одной
3. `oraclejdk8` - опять же, пока можно оставить так, но мы просим java9 (а 20 марта выйдет релиз java10 уже)
4. ResponseEntity - raw-тип не надо использовать, параметризуйте хотя вопросом.
5. Зачем первая строчка?
```
        httpSession.setAttribute("login", null);
        httpSession.invalidate();
```
6.

2018-04-05 10:17 UTC, 3kybika commented
Вроде бы все пофикшено. Переведено на рельсы БД, добавлены тесты - для второго РК.

2018-04-05 12:27 UTC, merged