RK2. Database (new)
java-park-mail-ru/shark_team-02-2018 pull request #3
Opened 2018-04-27 16:25 UTC by 3kybika

2018-04-27 16:28 UTC, 3kybika commented
Доброго времени суток!
Вроде бы все поправлено. Для миграций, добавил FlyWay, на 9ю версию java переделал.
Что-то еще нужно править?

2018-05-01 21:05 UTC, KSolovyev requested changes

2018-05-01 21:05 UTC, KSolovyev commented on src/test/java/park/sharkteam/UserControllerTest.java
> +                        .content(
я еще на карту просил переделать вот эти захардкоженные строки

2018-05-02 17:44 UTC, KSolovyev commented
@3kybika ?

2018-05-06 13:27 UTC, KSolovyev commented
парни, когда поправите?

2018-05-09 15:46 UTC, 3kybika commented
Извиняюсь, что задержался...
Исправил через JSONObject. Подойдет?

2018-05-09 15:58 UTC, KSolovyev commented
Нет, там не нужен JSONObject
Нужен простой Map.of()

2018-05-09 18:12 UTC, 3kybika commented
Таким образом?

2018-05-11 13:57 UTC, 3kybika commented
Исправил. 
Подойдет? Еще будут замечания?

2018-05-11 17:23 UTC, KSolovyev requested changes

2018-05-11 17:23 UTC, KSolovyev commented on src/test/java/park/sharkteam/UserControllerTest.java
> +                                new JSONObject(Map.of(
я думал там Object =(

Давайте тогда сделаем 
```
objectMapper.writeValueAsString(Map.of(
                                        "loginField","login",
                                        "emailField","user@mail.ru",
                                        "passwordField","password"
                                ))
```
это надо будет еще ObjectMapper заинжектить

2018-05-11 19:33 UTC, 3kybika commented
Готово!

2018-05-12 12:12 UTC, 3kybika commented
Подойдет?

2018-05-13 20:13 UTC, merged